name: ULCMap
main: com.ulcserver.map.Main
version: 1.0
author: Zeus233
commands:
 ulcmap:
   description: The Command For ULCTrap Plugin! 
   usage: 
   permission: ulcmap.use
   permission-message: Add Trap!

permissions:
  ulcmap.use:
      description: The Permission For Using Guide Command! 
      default: op

